# Generated by Django 6.0.2 on 2026-02-06 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True)),
                ('copy_number', models.CharField(max_length=100)),
                ('available_copies', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('DAMAGED', 'DAMAGED')], default='GOOD', max_length=20)),
                ('location', models.CharField(choices=[('STACK', 'STACK'), ('SHELF', 'SHELF')], default='STACK', max_length=20)),
                ('can_borrow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('OVERDUE', 'OVERDUE')], default='BORROWED', max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='backend.member')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='backend.physicalmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'RESERVED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='RESERVED', max_length=20)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='backend.physicalmaterial')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='backend.member')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='backend.borrow')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='backend.member')),
                ('reserve_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='backend.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='reserve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.reservation'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_material', to='backend.borrow')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER')], default='CASH', max_length=20)),
                ('transaction_refernce', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='backend.member')),
                ('return_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='backend.return')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('work_shift', models.CharField(blank=True, max_length=15, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_material', to='backend.staff'),
        ),
        migrations.AddField(
            model_name='physicalmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_material', to='backend.staff'),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('campus', models.CharField(max_length=100)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to='backend.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('format', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_material', to='backend.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulation', to='backend.member')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulation', to='backend.physicalmaterial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.staff')),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='backend.staff'),
        ),
    ]
