# Generated by Django 6.0.2 on 2026-03-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_fix_user_profiles_and_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='reserve_id',
        ),
        migrations.RemoveField(
            model_name='return',
            name='borrow_id',
        ),
    ]
