# Generated by Django 6.0.2 on 2026-03-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_borrow_created_by_remove_borrow_material_id_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='borrow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='transactions.borrow'),
        ),
        migrations.RemoveField(
            model_name='circulation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='circulation',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='circulation',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='digitalmaterial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='return_id',
        ),
        migrations.RemoveField(
            model_name='physicalmaterial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='reserve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='transactions.reservation'),
        ),
        migrations.RemoveField(
            model_name='return',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Circulation',
        ),
        migrations.DeleteModel(
            name='DigitalMaterial',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PhysicalMaterial',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
