# <<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-06 09:02
# =======
# Generated by Django 6.0.2 on 2026-03-04 07:37
# >>>>>>> 6cda79f11c21aad48fbb99f57000b21628f4dcd2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_notification_borrow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(default='piassa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='phone',
            field=models.CharField(default='piassa', max_length=100),
            preserve_default=False,
        ),
    ]
