# Generated by Django 6.0.2 on 2026-03-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_library_location_library_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to='backend.staff', unique=True),
        ),
    ]
