# Generated by Django 6.0.2 on 2026-03-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_library_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to='backend.staff'),
        ),
    ]
