# Generated by Django 6.0.2 on 2026-03-02 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0004_remove_borrow_created_by_remove_borrow_material_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('format', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_material', to='backend.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True)),
                ('copy_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('DAMAGED', 'DAMAGED')], default='GOOD', max_length=20)),
                ('location', models.CharField(choices=[('STACK', 'STACK'), ('SHELF', 'SHELF')], default='STACK', max_length=20)),
                ('can_borrow', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_material', to='backend.staff')),
            ],
        ),
    ]
