# Generated by Django 6.0.2 on 2026-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmaterial',
            name='file',
            field=models.FileField(default=0, upload_to='digital_materials/'),
            preserve_default=False,
        ),
    ]
