# Generated by Django 6.0.3 on 2026-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0002_digitalmaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalmaterial',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalmaterial',
            name='format',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
