# Generated by Django 6.0.2 on 2026-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0002_digitalmaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalmaterial',
            name='total_copies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
