# Generated by Django 6.0.2 on 2026-03-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0002_digitalmaterial_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalmaterial',
            old_name='available_copies',
            new_name='total_copies',
        ),
    ]
