# Generated by Django 6.0.2 on 2026-03-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0002_digitalmaterial_file_alter_digitalmaterial_file_size_and_more'),
        ('material_mgt', '0003_rename_available_copies_physicalmaterial_total_copies'),
    ]

    operations = [
    ]
