# Generated by Django 6.0.2 on 2026-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0004_merge_20260311_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalmaterial',
            name='file',
            field=models.FileField(default='File', upload_to='digital_materials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalmaterial',
            name='file_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='digitalmaterial',
            name='format',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalmaterial',
            name='copy_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
