# Generated by Django 6.0.2 on 2026-03-12 00:00

from django.db import migrations, models


def set_available_copies(apps, schema_editor):
    PhysicalMaterial = apps.get_model("material_mgt", "PhysicalMaterial")
    PhysicalMaterial.objects.filter(available_copies__isnull=True).update(
        available_copies=models.F("total_copies")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("material_mgt", "0005_alter_digitalmaterial_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalmaterial",
            name="available_copies",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="physicalmaterial",
            name="copy_number",
        ),
        migrations.RunPython(set_available_copies, migrations.RunPython.noop),
    ]

