# Generated by Django 5.2.7 on 2026-04-27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_mgt", "0006_remove_physicalmaterial_copy_number_add_available_copies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digital_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="material_mgt.digitalmaterial",
                    ),
                ),
                (
                    "physical_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "updated_at"], name="mfb_user_updated_idx"),
                    models.Index(fields=["physical_material", "updated_at"], name="mfb_phys_updated_idx"),
                    models.Index(fields=["digital_material", "updated_at"], name="mfb_digi_updated_idx"),
                    models.Index(fields=["rating"], name="mfb_rating_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        name="material_feedback_exactly_one_material",
                        condition=(
                            (models.Q(physical_material__isnull=False) & models.Q(digital_material__isnull=True))
                            | (models.Q(physical_material__isnull=True) & models.Q(digital_material__isnull=False))
                        ),
                    ),
                    models.CheckConstraint(
                        name="material_feedback_rating_range",
                        condition=models.Q(rating__gte=1, rating__lte=5),
                    ),
                    models.UniqueConstraint(
                        fields=["user", "physical_material"],
                        condition=models.Q(physical_material__isnull=False),
                        name="material_feedback_unique_user_physical",
                    ),
                    models.UniqueConstraint(
                        fields=["user", "digital_material"],
                        condition=models.Q(digital_material__isnull=False),
                        name="material_feedback_unique_user_digital",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialFavorite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "digital_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="material_mgt.digitalmaterial",
                    ),
                ),
                (
                    "physical_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="mfv_user_created_idx"),
                    models.Index(fields=["physical_material", "created_at"], name="mfv_phys_created_idx"),
                    models.Index(fields=["digital_material", "created_at"], name="mfv_digi_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        name="material_favorite_exactly_one_material",
                        condition=(
                            (models.Q(physical_material__isnull=False) & models.Q(digital_material__isnull=True))
                            | (models.Q(physical_material__isnull=True) & models.Q(digital_material__isnull=False))
                        ),
                    ),
                    models.UniqueConstraint(
                        fields=["user", "physical_material"],
                        condition=models.Q(physical_material__isnull=False),
                        name="material_favorite_unique_user_physical",
                    ),
                    models.UniqueConstraint(
                        fields=["user", "digital_material"],
                        condition=models.Q(digital_material__isnull=False),
                        name="material_favorite_unique_user_digital",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialBookmark",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "digital_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="material_mgt.digitalmaterial",
                    ),
                ),
                (
                    "physical_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="mbk_user_created_idx"),
                    models.Index(fields=["physical_material", "created_at"], name="mbk_phys_created_idx"),
                    models.Index(fields=["digital_material", "created_at"], name="mbk_digi_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        name="material_bookmark_exactly_one_material",
                        condition=(
                            (models.Q(physical_material__isnull=False) & models.Q(digital_material__isnull=True))
                            | (models.Q(physical_material__isnull=True) & models.Q(digital_material__isnull=False))
                        ),
                    ),
                    models.UniqueConstraint(
                        fields=["user", "physical_material"],
                        condition=models.Q(physical_material__isnull=False),
                        name="material_bookmark_unique_user_physical",
                    ),
                    models.UniqueConstraint(
                        fields=["user", "digital_material"],
                        condition=models.Q(digital_material__isnull=False),
                        name="material_bookmark_unique_user_digital",
                    ),
                ],
            },
        ),
    ]
