# Generated by Django 6.0.2 on 2026-03-02 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0004_remove_borrow_created_by_remove_borrow_material_id_and_more'),
        ('material_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.staff')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulation', to='material_mgt.physicalmaterial')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulation', to='backend.member')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'RESERVED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='RESERVED', max_length=20)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='material_mgt.physicalmaterial')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='backend.member')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('OVERDUE', 'OVERDUE')], default='BORROWED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='backend.staff')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='material_mgt.physicalmaterial')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='backend.member')),
                ('reserve_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_material', to='transactions.borrow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_material', to='backend.staff')),
            ],
        ),
    ]
