# Generated by Django 6.0.2 on 2026-03-12 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backend", "0004_remove_borrow_created_by_remove_borrow_material_id_and_more"),
        ("material_mgt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="backend.member",
                    ),
                ),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                ("reserve_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("RESERVED", "RESERVED"), ("EXPIRED", "EXPIRED"), ("CANCELLED", "CANCELLED")],
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["reserve_date"],
            },
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrows",
                        to="backend.member",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrows",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrows",
                        to="transactions.reservation",
                    ),
                ),
                ("borrow_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("BORROWED", "BORROWED"), ("OVERDUE", "OVERDUE")],
                        default="BORROWED",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_borrows",
                        to="backend.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circulation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="circulations",
                        to="backend.member",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="circulations",
                        to="material_mgt.physicalmaterial",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("BORROWED", "BORROWED"), ("RETURNED", "RETURNED")],
                        default="BORROWED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="circulations_created",
                        to="backend.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "borrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="transactions.borrow",
                    ),
                ),
                ("return_date", models.DateTimeField(auto_now_add=True)),
                ("fine_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns_created",
                        to="backend.staff",
                    ),
                ),
            ],
        ),
    ]
