# Generated by Django 6.0.2 on 2026-03-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_library_staff_id'),
        ('material_mgt', '0005_alter_digitalmaterial_file_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='material_mgt.physicalmaterial'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='backend.member'),
        ),
    ]
