# Generated by Django 6.0.2 on 2026-03-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
    ]
