# Generated by Django 6.0.2 on 2026-03-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_reservation_material_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE transactions_reservation RENAME COLUMN member_id_id TO member_id;",
            reverse_sql="ALTER TABLE transactions_reservation RENAME COLUMN member_id TO member_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_reservation RENAME COLUMN material_id_id TO material_id;",
            reverse_sql="ALTER TABLE transactions_reservation RENAME COLUMN material_id TO material_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_borrow RENAME COLUMN member_id_id TO member_id;",
            reverse_sql="ALTER TABLE transactions_borrow RENAME COLUMN member_id TO member_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_borrow RENAME COLUMN material_id_id TO material_id;",
            reverse_sql="ALTER TABLE transactions_borrow RENAME COLUMN material_id TO material_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_borrow RENAME COLUMN reserve_id_id TO reservation_id;",
            reverse_sql="ALTER TABLE transactions_borrow RENAME COLUMN reservation_id TO reserve_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_circulation RENAME COLUMN member_id_id TO member_id;",
            reverse_sql="ALTER TABLE transactions_circulation RENAME COLUMN member_id TO member_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_circulation RENAME COLUMN material_id_id TO material_id;",
            reverse_sql="ALTER TABLE transactions_circulation RENAME COLUMN material_id TO material_id_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_return RENAME COLUMN borrow_id_id TO borrow_id;",
            reverse_sql="ALTER TABLE transactions_return RENAME COLUMN borrow_id TO borrow_id_id;",
        ),
    ]
