# Generated by Django 6.0.2 on 2026-03-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_fix_legacy_fk_columns"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE transactions_reservation RENAME COLUMN member_id TO member_id_id;",
            reverse_sql="ALTER TABLE transactions_reservation RENAME COLUMN member_id_id TO member_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE transactions_reservation RENAME COLUMN material_id TO material_id_id;",
            reverse_sql="ALTER TABLE transactions_reservation RENAME COLUMN material_id_id TO material_id;",
        ),
    ]
