# Generated by Django 6.0.2 on 2026-03-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0006_remove_physicalmaterial_copy_number_add_available_copies'),
        ('transactions', '0005_use_user_for_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='material_mgt.physicalmaterial'),
        ),
    ]
