# Generated by Django 6.0.2 on 2026-04-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_reservation_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
