# Generated by Django 6.0.2 on 2026-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_borrow_overdue_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='availability_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
